### ISSUE TITLE
Request for QR scanner in mymonero web wallet on mobile

### ISSUE THREAD

**Issue by sillydroid** [mymonero/mymonero-web-js#26]
Hi,

Is there a plan to include a QR scanner in the mymonero web wallet please? To be activated when using mymonero on an appropriate mobile device.

My apology if this is an open issue, but searched through the list of open issues and could not see this captured in a roadmap anywhere. 

Cheers!

**Comment by devinpearson** [comment]
This library looks to be a good fit. https://github.com/zxing-js/library

**Comment by sillydroid** [comment]
> This library looks to be a good fit. https://github.com/zxing-js/library

Hi Devin thank you very much! :-)
