### ISSUE TITLE
Firefox issue with new fiat-to-crypto functionality

### ISSUE THREAD

**Issue by karlbuys** [mymonero/mymonero-web-js#36]
### Description

New fiat-to-crypto exchange functionality does not work on Firefox.

- [x] Can you reproduce the issue?  

### Steps to reproduce

1. Load the web wallet, log into a wallet and navigate to the exchange page
2. Using the currency selector, select 
3. [and so on...]

**Expected behavior:**

e.path is undefined

**Actual behavior:**

Currency to be selected

**Comment by devinpearson** [comment]
this has been resolved in v1.2.1 and has been deployed to our live environments
